//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatWithAI.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatWithAI.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached image.
        /// </summary>
        internal static string AttachedImage {
            get {
                return ResourceManager.GetString("AttachedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИ переведён в режим исходной модели без личности Виви..
        /// </summary>
        internal static string BaseModeNow {
            get {
                return ResourceManager.GetString("BaseModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной режим Виви включён..
        /// </summary>
        internal static string CommonModeNow {
            get {
                return ResourceManager.GetString("CommonModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;system_message&gt;If you have something to continue, please continue.&lt;/system_message&gt;.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a user&apos;s true friend..
        /// </summary>
        internal static string DefaultDescription {
            get {
                return ResourceManager.GetString("DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGI.
        /// </summary>
        internal static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневник ИИ очищен..
        /// </summary>
        internal static string DiaryCleared {
            get {
                return ResourceManager.GetString("DiaryCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневник ИИ пустой..
        /// </summary>
        internal static string DiaryEmpty {
            get {
                return ResourceManager.GetString("DiaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИ переведён в режим поддержки видео и .pdf файлов..
        /// </summary>
        internal static string DocsModeNow {
            get {
                return ResourceManager.GetString("DocsModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы и видео были скрыты так как не поддерживаются в сообщении..
        /// </summary>
        internal static string DocumentNotSupported {
            get {
                return ResourceManager.GetString("DocumentNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИ переведён в режим учителя английского языка..
        /// </summary>
        internal static string EnglishModeNow {
            get {
                return ResourceManager.GetString("EnglishModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка, попробуйте нажать кнопку &quot;Retry&quot;.
        ///Если не помогло после двух попыток - попробуйте начать новый чат, нажав на /start..
        /// </summary>
        internal static string ErrorTryAgain {
            get {
                return ResourceManager.GetString("ErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим проверки грамматики..
        /// </summary>
        internal static string GrammarModeNow {
            get {
                return ResourceManager.GetString("GrammarModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} has started!.
        /// </summary>
        internal static string HasStarted {
            get {
                return ResourceManager.GetString("HasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 *Базовые команды*:
        ////start — Перезапустить чат с нуля. ИИ больше не видит старых сообщений.
        ////clear — Очистить Дневник Виви. Дневник — это место, где она может делать свои заметки во время общения.
        ////help — Вывести список доступных команд.
        ///
        ///📚 *Команды для смены режима чата*:
        ////common — Включить основной режим работы Виви.
        ////photoeditor — Включить режим художника и фоторедактора.
        ////troll — Режим Виви-тролля, общающейся через подколы и юмор.
        ////grammar — Режим проверки грамматики.
        ////base — ИИ без личност [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Думаю... ⌛.
        /// </summary>
        internal static string InitAnswerTemplate {
            get {
                return ResourceManager.GetString("InitAnswerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет доступа к ИИ-боту. Пожалуйста, обратитесь к администратору бота, чтобы запросить доступ..
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only text or photo messages are allowed..
        /// </summary>
        internal static string OnlyTextOrPhoto {
            get {
                return ResourceManager.GetString("OnlyTextOrPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИ переведён в режим создателя изображений и редактора фотографий.
        ///⚠️ В этом специализированном режиме не поддерживается приём голосовых сообщений..
        /// </summary>
        internal static string PhotoEditorModeNow {
            get {
                return ResourceManager.GetString("PhotoEditorModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /common - чтобы вернуться в обычный режим Виви..
        /// </summary>
        internal static string ReturnNote {
            get {
                return ResourceManager.GetString("ReturnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assistant.
        /// </summary>
        internal static string RoleAssistant {
            get {
                return ResourceManager.GetString("RoleAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function.
        /// </summary>
        internal static string RoleFunction {
            get {
                return ResourceManager.GetString("RoleFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        internal static string RoleSystem {
            get {
                return ResourceManager.GetString("RoleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИ переведён в режим учёного..
        /// </summary>
        internal static string ScientistModeNow {
            get {
                return ResourceManager.GetString("ScientistModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так. 😓 Извините... Пожалуйста, попробуйте еще раз..
        /// </summary>
        internal static string SomethingGoesWrong {
            get {
                return ResourceManager.GetString("SomethingGoesWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 Начат новый чат в /{0} режиме!
        ///
        ///ИИ забыл предыдущую беседу, однако сохранил доступ к заметкам в своём Дневнике.
        ///
        ///Памятка:{1}
        ////help - вывести полный список доступных команд.
        ////clear - очистить Дневник ИИ.
        ///
        ///⚠️ Важно: ИИ может ошибаться, причём уверенно!
        ///Пожалуйста, перепроверяйте всю важную информацию. .
        /// </summary>
        internal static string StartWarning {
            get {
                return ResourceManager.GetString("StartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИ переведён в режим учителя..
        /// </summary>
        internal static string TeacherModeNow {
            get {
                return ResourceManager.GetString("TeacherModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИИ переведён в режим терапевта..
        /// </summary>
        internal static string TherapistModeNow {
            get {
                return ResourceManager.GetString("TherapistModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😈.
        /// </summary>
        internal static string TrollModeNow {
            get {
                return ResourceManager.GetString("TrollModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User comment.
        /// </summary>
        internal static string UserComment {
            get {
                return ResourceManager.GetString("UserComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;system_message&gt;The user has sent you a picture. What do you think?&lt;/system_message&gt;.
        /// </summary>
        internal static string WhatIsOnTheImage {
            get {
                return ResourceManager.GetString("WhatIsOnTheImage", resourceCulture);
            }
        }
    }
}
