//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatWithAI.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatWithAI.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached image.
        /// </summary>
        internal static string AttachedImage {
            get {
                return ResourceManager.GetString("AttachedImage", resourceCulture);
            }
        }
        
        internal static string BaseModeNow {
            get {
                return ResourceManager.GetString("BaseModeNow", resourceCulture);
            }
        }
        
        internal static string CommonModeNow {
            get {
                return ResourceManager.GetString("CommonModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;system_message&gt;If you have something to continue, please continue.&lt;/system_message&gt;.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a user&apos;s true friend..
        /// </summary>
        internal static string DefaultDescription {
            get {
                return ResourceManager.GetString("DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGI.
        /// </summary>
        internal static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        internal static string DiaryCleared {
            get {
                return ResourceManager.GetString("DiaryCleared", resourceCulture);
            }
        }
        
        internal static string DiaryEmpty {
            get {
                return ResourceManager.GetString("DiaryEmpty", resourceCulture);
            }
        }
        
        internal static string DocsModeNow {
            get {
                return ResourceManager.GetString("DocsModeNow", resourceCulture);
            }
        }
        
        internal static string DocumentNotSupported {
            get {
                return ResourceManager.GetString("DocumentNotSupported", resourceCulture);
            }
        }
        
        internal static string EnglishModeNow {
            get {
                return ResourceManager.GetString("EnglishModeNow", resourceCulture);
            }
        }
        
        internal static string ErrorTryAgain {
            get {
                return ResourceManager.GetString("ErrorTryAgain", resourceCulture);
            }
        }
        
        internal static string GrammarModeNow {
            get {
                return ResourceManager.GetString("GrammarModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} has started!.
        /// </summary>
        internal static string HasStarted {
            get {
                return ResourceManager.GetString("HasStarted", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string InitAnswerTemplate {
            get {
                return ResourceManager.GetString("InitAnswerTemplate", resourceCulture);
            }
        }
        
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only text or photo messages are allowed..
        /// </summary>
        internal static string OnlyTextOrPhoto {
            get {
                return ResourceManager.GetString("OnlyTextOrPhoto", resourceCulture);
            }
        }
        
        internal static string PhotoEditorModeNow {
            get {
                return ResourceManager.GetString("PhotoEditorModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        internal static string ReturnNote {
            get {
                return ResourceManager.GetString("ReturnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assistant.
        /// </summary>
        internal static string RoleAssistant {
            get {
                return ResourceManager.GetString("RoleAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function.
        /// </summary>
        internal static string RoleFunction {
            get {
                return ResourceManager.GetString("RoleFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        internal static string RoleSystem {
            get {
                return ResourceManager.GetString("RoleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        internal static string ScientistModeNow {
            get {
                return ResourceManager.GetString("ScientistModeNow", resourceCulture);
            }
        }
        
        internal static string SomethingGoesWrong {
            get {
                return ResourceManager.GetString("SomethingGoesWrong", resourceCulture);
            }
        }
        
        internal static string StartWarning {
            get {
                return ResourceManager.GetString("StartWarning", resourceCulture);
            }
        }
        
        internal static string TeacherModeNow {
            get {
                return ResourceManager.GetString("TeacherModeNow", resourceCulture);
            }
        }
        
        internal static string TherapistModeNow {
            get {
                return ResourceManager.GetString("TherapistModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😈.
        /// </summary>
        internal static string TrollModeNow {
            get {
                return ResourceManager.GetString("TrollModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User comment.
        /// </summary>
        internal static string UserComment {
            get {
                return ResourceManager.GetString("UserComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;system_message&gt;The user has sent you a picture. What do you think?&lt;/system_message&gt;.
        /// </summary>
        internal static string WhatIsOnTheImage {
            get {
                return ResourceManager.GetString("WhatIsOnTheImage", resourceCulture);
            }
        }
    }
}
