//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatWithAI.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatWithAI.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached image.
        /// </summary>
        internal static string AttachedImage {
            get {
                return ResourceManager.GetString("AttachedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI has been switched to the base model mode without any persona..
        /// </summary>
        internal static string BaseModeNow {
            get {
                return ResourceManager.GetString("BaseModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI main mode is enabled..
        /// </summary>
        internal static string CommonModeNow {
            get {
                return ResourceManager.GetString("CommonModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;system_message&gt;If you have something to continue, please continue.&lt;/system_message&gt;.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a user&apos;s true friend..
        /// </summary>
        internal static string DefaultDescription {
            get {
                return ResourceManager.GetString("DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        internal static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AI Diary has been cleared..
        /// </summary>
        internal static string DiaryCleared {
            get {
                return ResourceManager.GetString("DiaryCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AI Diary is empty..
        /// </summary>
        internal static string DiaryEmpty {
            get {
                return ResourceManager.GetString("DiaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI has been switched to video and PDF support mode..
        /// </summary>
        internal static string DocsModeNow {
            get {
                return ResourceManager.GetString("DocsModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents and videos were hidden because they are not supported in the message..
        /// </summary>
        internal static string DocumentNotSupported {
            get {
                return ResourceManager.GetString("DocumentNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI has been switched to English teacher mode..
        /// </summary>
        internal static string EnglishModeNow {
            get {
                return ResourceManager.GetString("EnglishModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try pressing the &quot;Retry&quot; button.
        ///If it still does not help after two attempts, try starting a new chat by pressing /start..
        /// </summary>
        internal static string ErrorTryAgain {
            get {
                return ResourceManager.GetString("ErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar check mode..
        /// </summary>
        internal static string GrammarModeNow {
            get {
                return ResourceManager.GetString("GrammarModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} has started!.
        /// </summary>
        internal static string HasStarted {
            get {
                return ResourceManager.GetString("HasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 *Basic commands*:
        ////start — Restart the chat from scratch. AI will no longer see old messages.
        ////clear — Clear the AI Diary. The Diary is a place where it can make notes during the conversation.
        ////help — Show the list of available commands.
        ///
        ///📚 *Commands to switch chat mode*:
        ////common — Enable the main AI mode.
        ////photoeditor — Enable artist and photo editor mode.
        ////troll — AI troll mode, communicating through teasing and humor.
        ////grammar — Grammar check mode.
        ////base — AI without any persona, in its ori [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking... ⌛.
        /// </summary>
        internal static string InitAnswerTemplate {
            get {
                return ResourceManager.GetString("InitAnswerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the AI bot. Please contact the bot administrator to request access..
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only text or photo messages are allowed..
        /// </summary>
        internal static string OnlyTextOrPhoto {
            get {
                return ResourceManager.GetString("OnlyTextOrPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI has been switched to image creation and photo editing mode.
        ///⚠️ Voice messages are not supported in this specialized mode..
        /// </summary>
        internal static string PhotoEditorModeNow {
            get {
                return ResourceManager.GetString("PhotoEditorModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /common - to return to the normal AI mode..
        /// </summary>
        internal static string ReturnNote {
            get {
                return ResourceManager.GetString("ReturnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assistant.
        /// </summary>
        internal static string RoleAssistant {
            get {
                return ResourceManager.GetString("RoleAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function.
        /// </summary>
        internal static string RoleFunction {
            get {
                return ResourceManager.GetString("RoleFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        internal static string RoleSystem {
            get {
                return ResourceManager.GetString("RoleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI has been switched to scientist mode..
        /// </summary>
        internal static string ScientistModeNow {
            get {
                return ResourceManager.GetString("ScientistModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. 😓 Sorry... Please try again..
        /// </summary>
        internal static string SomethingGoesWrong {
            get {
                return ResourceManager.GetString("SomethingGoesWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 A new chat has been started in /{0} mode!
        ///
        ///AI has forgotten the previous conversation, but still has access to notes in its Diary.
        ///
        ///Reminder:{1}
        ////help - show the full list of available commands.
        ////clear - clear the AI Diary.
        ///
        ///⚠️ Important: AI can make mistakes, and sometimes very confidently!
        ///Please double-check all important information..
        /// </summary>
        internal static string StartWarning {
            get {
                return ResourceManager.GetString("StartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI has been switched to teacher mode..
        /// </summary>
        internal static string TeacherModeNow {
            get {
                return ResourceManager.GetString("TeacherModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI has been switched to therapist mode..
        /// </summary>
        internal static string TherapistModeNow {
            get {
                return ResourceManager.GetString("TherapistModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😈.
        /// </summary>
        internal static string TrollModeNow {
            get {
                return ResourceManager.GetString("TrollModeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User comment.
        /// </summary>
        internal static string UserComment {
            get {
                return ResourceManager.GetString("UserComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;system_message&gt;The user has sent you a picture. What do you think?&lt;/system_message&gt;.
        /// </summary>
        internal static string WhatIsOnTheImage {
            get {
                return ResourceManager.GetString("WhatIsOnTheImage", resourceCulture);
            }
        }
    }
}
